# Setup
title:               Jisu's Blog
tagline:             'Until Die'
description:         'No Post Blog Made by <a href="https://instagram.com/zzzzsuzz" target="_blank">@zzzzsuzz</a>.'
url:                 https://jisuzzzz.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jisu Kim
  url:               https://instagram.com/zzzzsuzz
  email:             meked@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
